### ISSUE TITLE
Can you release the library?

### ISSUE THREAD

**Issue by jabrena** [pablo127/gmail-api-sample#1]
Hi,

I read your article:
https://medium.com/@pablo127/sending-emails-from-java-app-with-gmail-api-eac23ca0eb5

and I would like to know if you are going to release the library.

Is it possible if you follow SEMVER? 
https://semver.org/

currently is:

`version '1.0-SNAPSHOT'`

but it should be: `1.0.0-SNAPSHOT`.

https://jitpack.io/#pablo127/gmail-api-sample

Many thanks in advance.

Juan Antonio

**Comment by plswiderski** [comment]
Hello Juan,
It is really nice to hear that you've read my article.
It was not in my plans to release this project because it is a sample. I expect that you just copy paste the code and adjust it to your requirements.
The project follows SEMVER, I just assume that when there is no PATCH it is 0 as default. Probably you are right that it is not completely good approach so I change it. Spring core used to be like that but they changed and there is always PATCH part (http://mvnrepository.com/artifact/org.springframework/spring-core) right now.

Thank you for the issue. I hope I helped. If not, do not hesitate to write again.
